name: DisKount
packages:
  Kingfisher:
    url: https://github.com/onevcat/Kingfisher.git
    from: 7.3.2
options:
  bundleIdPrefix: com.github.lupuuss
targets:
  DisKount:
    type: application
    platform: iOS
    deploymentTarget: 14.1
    sources: [DisKount]
    dependencies:
      - package: Kingfisher
